community/urls.py
from django.conf.urls import url

from . import views

app_name = 'community'

urlpatterns = [
    url(
        r'^(?P<slug>[\w.@+-]+)/ranking_table/$',
        views.ranking_table,
        name='ranking_table',
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/ranking_api/$',
        views.ranking_api,
        name='ranking_api',
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/$',
        views.community_page,
        name='community_page',
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/ranking/$',
        views.community_ranking,
        name='community_ranking',
    ),
    url(
        r'^admin/list/$',
        views.admin_community_list,
        name='admin_community_list',
    ),
    url(
        r'^admin/create/$',
        views.admin_community_create,
        name='admin_community_create',
    ),
    url(
        r'^admin/delete/(?P<pk>[0-9]+)/$',
        views.admin_community_delete,
        name='admin_community_delete',
    ),
    url(
        r'^admin/update/(?P<pk>[0-9]+)/$',
        views.AdminCommunityUpdate.as_view(success_url='/community/admin/list/'),
        name='admin_community_update',
    ),
    url(
        r'^(?P<pk>[0-9]+)/admin/manage/$',
        views.manage_admins,
        name='manage_admins',
    ),
    url(
        r'^(?P<pk>[0-9]+)/users/$',
        views.admin_user_list,
        name='admin_user_list',
    ),
    url(
        r'^(?P<pk>[0-9]+)/invite/$',
        views.admin_invite_user,
        name='admin_invite_user',
    ),
    url(
        r'^update/(?P<pk>[0-9]+)/$',
        views.CommunityUpdate.as_view(),
        name='community_update',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/join/(?P<user_pk>[0-9]+)/$',
        views.community_join,
        name='community_join',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/quit/(?P<user_pk>[0-9]+)/$',
        views.community_quit,
        name='community_quit',
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/results/$',
        views.community_results_page,
        name='community_resutls',
    ),
    url(
        r'^$',
        views.community_list,
        name='community_list',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/create/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/league/copy/(?P<copy_from_pk>[0-9]+)/$',
        views.CommunityLeagueEventCreate.as_view(),
        name='create_league',
    ),
    url(
        r'^league/(?P<pk>[0-9]+)/update/$',
        views.CommunityLeagueEventUpdate.as_view(),
        name='update_league',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/tournament/create/$',
        views.CommunityTournamentCreate.as_view(),
        name='create_tournament',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/calendar/create-event/$',
        views.CommunityEventCreate.as_view(),
        name='create_event',
    ),
    url(
        r'^(?P<community_pk>[0-9]+)/calendar/create-category/$',
        views.CommunityCategoryCreate.as_view(),
        name='create_category',
    ),
    url(
        r'^(?P<slug>[\w.@+-]+)/calendar/iframe/$',
        views.calendar_iframe,
        name='calendar_iframe',
    ),
]

wgo/urls.py
from django.conf.urls import url

from . import views

app_name = 'wgo'


urlpatterns = [
    url(
        r'^tsumego-api/$',
        views.tsumego_api,
        name='tsumego_api',
    ),
]

community/forms.py
from django import forms
from django.forms import ModelForm
from machina.models.fields import MarkupTextFieldWidget

from league.models import User

from .models import Community


class AdminCommunityForm(ModelForm):
    class Meta:
        model = Community

        fields = [
            'name',
            'slug',
            'description',
            'private_description',
            'close',
            'private',
            'promote',
            'locale',
            'timezone',
            'discord_webhook_url',
        ]
        widgets = {
            'description': MarkupTextFieldWidget(attrs={'placeholder': 'Public description of the community.'}),
            'private_description': MarkupTextFieldWidget(attrs={'placeholder': 'Only community members can see it.'}),
        }

        help_texts = {
            'name': 'Name of the community',
            'slug': 'Short slug to identify the community. URL will be https://openstudyroom.org/community/slug/',
            'close': "If close, it's invitation only community. Otherwise, anyone can join.",
            'private': 'If private, only members can see the community.',
            'promote': "If promoted, it's leagues will be shown to everyone in leagues views (same as OSR leagues).",
            'locale': 'The language used to send notifications.',
            'timezone': 'Timezone used to format dates in notifications.',
            'discord_webhook_url': 'Discord webhook url to send notifications.',
        }


class CommunityForm(ModelForm):
    class Meta:
        model = Community
        fields = [
            'description',
            'private_description',
            'close',
            'private',
            'discord_webhook_url',
        ]

        widgets = {
            'description': MarkupTextFieldWidget(attrs={'placeholder': 'Public description of the community.'}),
            'private_description': MarkupTextFieldWidget(attrs={'placeholder': 'Only community members can see it.'}),
        }

        help_texts = {
            'close': "If close, it's invitation only community. Otherwise, anyone can join.",
            'private': 'If private, only members can see the community.',
            'discord_webhook_url': 'Discord webhook url to send notifications',
        }


class CommunytyUserForm(forms.Form):
    username = forms.CharField(label='username')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username__iexact=username).exists():
            message = "We don't have a user with username" + username + '.'
            raise forms.ValidationError(message)
        return username


class CommunityRankingForm(forms.Form):
    begin_time = forms.DateField(
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}),
    )
    end_time = forms.DateField(
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control'}),
    )
    ffg_rating = forms.BooleanField(
        initial=True,
        required=False,
        label='FFG Rating',
        widget=forms.CheckboxInput(),
    )

community/views.py
from datetime import datetime

from dateutil.relativedelta import relativedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.http import require_POST
from django.views.generic.edit import UpdateView
from pytz import utc

from fullcalendar.views import CategoryCreate, PublicEventCreate
from league.forms import ActionForm
from league.models import LeagueEvent, User
from league.views import LeagueEventCreate, LeagueEventUpdate
from tournament.views import TournamentCreate

from .forms import AdminCommunityForm, CommunityForm, CommunityRankingForm, CommunytyUserForm
from .models import Community


@login_required()
@user_passes_test(User.is_osr_admin, login_url='/', redirect_field_name=None)
def admin_community_list(request):
    communitys = Community.objects.all()
    return render(request, 'community/admin/community_list.html', {'communitys': communitys})


@login_required()
@user_passes_test(User.is_osr_admin, login_url='/', redirect_field_name=None)
def admin_community_create(request):
    if request.method == 'POST':
        form = AdminCommunityForm(request.POST)
        if form.is_valid():
            community = Community.create(
                form.cleaned_data['name'],
                form.cleaned_data['slug'],
            )
            community.save()
            return HttpResponseRedirect(reverse('community:admin_community_list'))
    else:
        form = AdminCommunityForm
    return render(request, 'community/admin/community_create.html', {'form': form})


class AdminCommunityUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = AdminCommunityForm
    model = Community
    template_name_suffix = '_admin_update'

    def test_func(self):
        user = self.request.user
        return user.is_authenticated and user.is_osr_admin()

    def get_login_url(self):
        return '/'


class CommunityUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = CommunityForm
    model = Community
    template_name_suffix = '_update'

    def get_success_url(self):
        return reverse(
            'community:community_page',
            kwargs={'slug': self.get_object().slug},
        )

    def test_func(self):
        user = self.request.user
        return self.get_object().is_admin(user)

    def get_login_url(self):
        return '/'


@login_required()
@user_passes_test(User.is_osr_admin, login_url='/', redirect_field_name=None)
def admin_community_delete(request, pk):
    community = get_object_or_404(Community, pk=pk)
    if request.method == 'POST':
        admin_group = community.admin_group
        user_group = community.user_group
        community.delete()
        admin_group.delete()
        if user_group is not None:
            user_group.delete()
        return HttpResponseRedirect(reverse('community:admin_community_list'))

    else:
        raise Http404('What are you doing here?')


def community_page(request, slug):
    """ Main community view.

    Shows community descriptions, leagues, tournaments, members and games.
    """

    community = get_object_or_404(Community, slug=slug)

    if community.private and not community.is_member(request.user):
        raise Http404('What are you doing here?')

    # check rights
    admin = community.is_admin(request.user)
    # we should have a can_join method
    can_join = request.user.is_authenticated and \
        request.user.is_league_member() and \
        not community.is_member(request.user) and \
        not community.close

    # get leagues and tournaments
    leagues = community.leagueevent_set.all()
    if not admin:
        leagues = leagues.filter(is_public=True)
    tournaments = leagues.filter(event_type='tournament')
    leagues = leagues.exclude(event_type='tournament')

    # get members
    members = User.objects.filter(groups=community.user_group).select_related('profile')
    admins = members.filter(groups=community.admin_group)
    new_members = User.objects.\
        filter(groups=community.new_user_group).\
        filter(groups__name='league_member').\
        select_related('profile').\
        prefetch_related('discord_user')

    # get calendar data
    calendar_data = {}
    calendar_data['community'] = community.format()
    if request.user.is_authenticated:
        calendar_data['user'] = request.user.format()

    context = {
        'community': community,
        'leagues': leagues,
        'tournaments': tournaments,
        'admin': admin,
        'can_join': can_join,
        'can_quit': community.user_group in request.user.groups.all(),
        'members': members,
        'admins': admins,
        'new_members': new_members,
        'start_time_range': request.user.profile.start_cal if request.user.is_authenticated else 0,
        'end_time_range':  request.user.profile.end_cal if request.user.is_authenticated else 0,
        'public_events': community.publicevent_set.all(),
        'categories': community.category_set.all(),
        'calendar_data': calendar_data,
    }
    return render(request, 'community/community_page.html', context)

def ranking_table(request, slug):
    community = get_object_or_404(Community, slug=slug)

    if community.private and not community.is_member(request.user):
        raise Http404('What are you doing here?')

    # default to last year

    ranking_from = (datetime.now() - relativedelta(years=1)).strftime('%Y-%m-%d')
    ranking_to = datetime.now().strftime('%Y-%m-%d')

    context = {
        'community': community,
        'url_pattern':f'/community/{slug}/ranking_api/?begin_time=<RANKING_FROM>&end_time=<RANKING_TO>',
        'ranking_from':ranking_from,
        'ranking_to':ranking_to,
        'datatable_config':{
            'columns':[
                {'title':'Name', 'key':'full_name'},
                {'title':'# Games', 'key':'games_count'},
                {'title':'# Wins', 'key':'wins_count'},
                {'title':'Win ratio (%)', 'key':'win_ratio'},
                {'title':'FFG Rating', 'key':'ffg_rating'},
                {'title':'FFG Rank', 'key':'ffg_rank'},
            ],
            'id':'community_ranking_table',
            'url':f'/community/{slug}/ranking_api/?begin_time={ranking_from}&end_time={ranking_to}',
        },
    }

    return render(request, 'community/ranking_table.html', context)

def ranking_api(request, slug):
    """
    Shows community league ranking as a data JSON
    """
    # load the input params
    form = CommunityRankingForm(request.GET)
    if not form.is_valid():
        raise Http404('Invalid params')
    begin_time = datetime.combine(form.cleaned_data['begin_time'], datetime.min.time(), utc)
    end_time = datetime.combine(form.cleaned_data['end_time'], datetime.min.time(), utc)

    # load the community
    community = get_object_or_404(Community, slug=slug)

    if community.private and not community.is_member(request.user):
        raise Http404('What are you doing here?')

    if begin_time >= end_time:
        raise Http404('End time should be later than begin time')

    data = community.ranking(begin_time=begin_time, end_time=end_time)

    return JsonResponse(data)

def community_ranking(request, slug):
    """
    Shows community league ranking.
    """
    community = get_object_or_404(Community, slug=slug)

    if community.private and not community.is_member(request.user):
        raise Http404('What are you doing here?')

    if request.method == 'POST':
        form = CommunityRankingForm(request.POST)
        if form.is_valid():
            # format inc dates
            begin_time = datetime.combine(form.cleaned_data['begin_time'], datetime.min.time(), utc)
            end_time = datetime.combine(form.cleaned_data['end_time'], datetime.min.time(), utc)
            ffg_rating = form.cleaned_data['ffg_rating']

            if begin_time < end_time:

                data = community.ranking(begin_time=begin_time, end_time=end_time)

                # Create the file's content
                txt = f"{community.name}'s ranking from {begin_time.date()} to {end_time.date()}\n"

                for (stat_name, stat_sort) in [
                    ('Played games', 'games_count'),
                    ('Games won', 'wins_count'),
                    ('Win ratio (%)', 'win_ratio'),
                ]:
                    txt += '\n-------------------\n'+stat_name+' :\n-------------------\n'
                    txt += '\n'.join([
                        f'{d["full_name"]} {d[stat_sort]}'
                        for d in sorted(data['data'], key=lambda el, ss=stat_sort: el[ss], reverse=True)
                    ])


                if ffg_rating:
                    txt += '\n-------------------\nFFG Rating :\n-------------------\n'
                    txt += '\n'.join([
                        f'{d["full_name"]} {d["ffg_rating"] (d["ffg_rank"])}'
                        for d in sorted(data['data'], key=lambda el: el['ffg_rating'], reverse=True)
                    ])

                filename = 'OSR-community-ranking.txt'
                response = HttpResponse(txt, content_type='text/plain')
                response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
                return response

    context = {
        'community': community,
        'form': CommunityRankingForm,
    }

    return render(request, 'community/community_ranking.html', context)

def community_list(request):
    groups = request.user.groups.all()

community/templates/community/community_page.html
{% extends 'full_width.html' %}
{% load bootstrap3 league_tags static forum_markup_tags i18n tz %}
{% block title %}OSR - {{community.name}}{% endblock %}
{% block extra_head_js %}
{% get_current_language as LANGUAGE_CODE %}

<link rel='stylesheet' type="text/css" href="{%static 'fullcalendar/styles/fullcalendar.css'%}"/>
<link rel='stylesheet' type="text/css" href="{%static 'fullcalendar/styles/rangeslider.css'%}"/>
<link rel='stylesheet' type="text/css" href="{%static 'fullcalendar/styles/micromodal.css'%}"/>
<link rel='stylesheet' type="text/css" href="{%static 'fullcalendar/styles/custom.css'%}"/>
<script src='https://cdn.jsdelivr.net/npm/moment@2.27.0/min/moment.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.7.0/main.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.7.0/locales-all.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/@fullcalendar/moment@5.5.0/main.global.min.js'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/js/ion.rangeSlider.min.js"></script>
<script src="https://unpkg.com/micromodal/dist/micromodal.min.js"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>

<link rel='stylesheet' type="text/css" href="{%static 'css/sidemenu.css'%}"/>

<link rel='stylesheet' href='https://cdn.jsdelivr.net/qtip2/3.0.3/basic/jquery.qtip.min.css'/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.8.1/css/bootstrap-slider.min.css" />
<script
    src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
    integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
    crossorigin="anonymous">
</script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.13/dataRender/datetime.js"></script>
<script src='https://cdn.jsdelivr.net/qtip2/3.0.3/basic/jquery.qtip.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.8.1/bootstrap-slider.min.js'></script>

<script type="text/javascript">
function load_game(game_id) {
    $.ajax({
    type: "GET",
    url: "/league/game/json/" + game_id,
    dataType: "json",
    success: processData,
    error: function(){ alert("failed"); }
});

function processData(data)
{
    document.getElementById("game_infos").innerHTML= data.game_infos ;
    var elem = document.getElementById("player");
    var player = new WGo.BasicPlayer(elem, {
      sgf: data.sgf
      });
    $("[data-toggle=tooltip]").tooltip();

};
return false;};

</script>
{% endblock %}

{% block heading %}
<div class="page-header">
    <h1> {{community.name}}  </h1>
</div>
{%endblock%}
{% block content %}
{% get_current_timezone as TIME_ZONE %}
<div class="panel panel-default">
<div class="panel-heading clearfix">
  <h3> {{community.name}} ({{community.slug}})
  {% if admin %}
  <a href="{% url 'community:community_update' community.pk %}"><button class="btn btn-default pull-right">{% bootstrap_icon 'wrench' %} {% trans "Edit" %} </button></a>
  {% endif %}
  {% if can_join %}
  <form action=" {% url 'community:community_join' community.pk request.user.pk %}" method="post" >
    {% csrf_token %}
    <div class="form-group">
    <input type="hidden" name="action" value="join">
    <input type="hidden" name="next" value="{{request.path}}">
    <button type="submit" class="btn btn-success pull-right"  onclick="return confirm('
    {% blocktrans with name=community.name %}You are about to join the {{name}} community. Allright? {% endblocktrans %}
    ')">
    {% bootstrap_icon "ok" %} {% blocktrans with community_name=community.name %}Join {{community_name}} !{% endblocktrans %}
    </button>
    </div>
    </form>
  {% endif %}
  {% if can_quit %}
  <form action=" {% url 'community:community_quit' community.pk request.user.pk %}" method="post" >
    {% csrf_token %}
    <div class="form-group">
    <input type="hidden" name="action" value="join">
    <input type="hidden" name="next" value="{{request.path}}">
    <button type="submit" class="btn btn-danger pull-right"  onclick="return confirm('
    {% blocktrans with name=community.name %}You are about to quit the {{name}} community. Allright?{% endblocktrans %}
    ')">
    {% bootstrap_icon "remove" %} {% blocktrans with community_name=community.name %}Quit {{community_name}} !{% endblocktrans %}
    </button>
    </div>
    </form>
  {% endif %}

</h3>
</div>
<div class="panel-body">
<p>{{community.description|safe|rendered}}</p>
{% if can_quit %}
<p>{{community.private_description|safe|rendered}}</p>
{% endif %}
</div>
</div>

{% if admin %}
  {% include "community/includes/new_user_table.html"%}
{% endif %}


<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#leagues">{% trans "Leagues" %}</a></li>
  <li><a data-toggle="tab" href="#tournaments">{% trans "Tournaments" %}</a></li>
  <li><a data-toggle="tab" href="#games" id="games_tab">{% trans "Games" %}</a></li>
  <li><a data-toggle="tab" href="#members">{% trans "Members" %}</a></li>
  <li><a data-toggle="tab" href="#activity">{% trans "Activity" %}</a></li>
  {% if admin %}
  <li><a data-toggle="tab" href="#events">{% trans "Events" %}</a></li>
  {% endif %}
</ul>

<div class="tab-content">

  <div id="leagues" class="panel panel-default tab-pane fade in active">
    <div class="panel-heading clearfix">
      <h3>
        {% blocktrans with community_name=community.name %}All {{community_name}} leagues {% endblocktrans %}
        {% if admin %}
        <a href="{% url 'community:create_league' community.pk %}">
          <button class="btn btn-success pull-right">
            {% bootstrap_icon 'plus' %}
            {% trans "Create new league" %}
          </button>
        </a>
        {% endif %}
      </h3>
      {% trans "Open leagues are green." %}
    </div>
    {% include "community/includes/leagues_table.html" with leagues=leagues%}
  </div>

  <div id="games" class="panel panel-default tab-pane fade in">
    <div class="panel-heading">
      <h3>{% blocktrans with community_name=community.name %}{{community_name}} games{% endblocktrans %}</h3>
    </div>
    <div class ="row">
      <div class="col-md-4">
        <div id ="game_infos"></div>
        {% include "league/includes/games.html" with community=community %}
      </div>
      <div class="col-md-8">
        <div id="player">
          <div class="alert alert-info">
            {% trans "Click a game result to see it." %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="activity" class="panel panel-default tab-pane fade in">
    <div id='calendar' class="panel-body"></div>
    <!-- Modal forms -->
    {% include 'fullcalendar/includes/modal.html' %}
  </div>

  <div id="tournaments" class="panel panel-default tab-pane fade">
    <div class="panel-heading clearfix">
      <h3>
        {% blocktrans with community_name=community.name %}All {{community_name}} tournaments {% endblocktrans %}
        {% if admin %}
        <a href="{% url 'community:create_tournament' community.pk %}">
          <button class="btn btn-success pull-right">
            {% bootstrap_icon 'plus' %}
            {% trans "Create new tournament" %}
          </button>
        </a>
        {% endif %}
      </h3>
    {% trans "Open tournament are green." %}
    </div>
    {% include "community/includes/tournaments_table.html" with leagues=tournaments%}
  </div>


  <div id="members" class="panel panel-default tab-pane fade">
    <div class="panel-heading clearfix">
      <h3> {% blocktrans with community_name=community.name %}All {{community_name}} members {% endblocktrans %} </h3>
      {% if admin %}
        <div class="pull-right">
          {% trans "Invite a user" %}
          <form action=" {% url 'community:admin_invite_user' community.pk %}" method="post" >
            {% csrf_token %}
            <div class="form-group">
              <input type="text" name="username" placeholder="{% trans 'OSR exact username' %}" >
              <button type="submit" class="btn btn-success btn-sm"  >
              {% bootstrap_icon "ok" %} {% trans "Invite  !" %}
              </button>
            </div>
          </form>
        </div>
      {% endif %}
    </div>
  {% trans "Community admins are blue." %}
  {% include "community/includes/members_table.html" with members=members%}
  </div>

</div>

{% if admin %}
  <div id="events" class="panel panel-default tab-pane fade">
      <legend>
      Categories
      <a  href="{%url 'community:create_category' community.pk %}">
        <button class="btn btn-xs btn-success pull-right clearfix">
          {%bootstrap_icon 'plus'%} {% trans "Create a new category" %}
        </button>
      </a>
      </legend>
    {% include 'fullcalendar/includes/admin_category_table.html' %}

      <legend>
      Events
      <a  href="{%url 'community:create_event' community.pk %}">
        <button class="btn btn-xs btn-success pull-right clearfix">
          {%bootstrap_icon 'plus'%} {% trans "Create a new event" %}
        </button>
      </a>
      </legend>
    {% include 'fullcalendar/includes/admin_event_table.html' %}

  </div>
{% endif %}

{% endblock %}

{% block extra_js %}
{% get_current_timezone as TIME_ZONE %}
{% get_current_language as LANGUAGE_CODE %}

{% if admin %}
  <script src={%static 'league/js/manage_league_user.js'%}></script>
{% endif %}
<script>
{% include 'league/includes/ajax_setup.html' %}
</script>
<!--
{% if can_quit %}
  <script src={%static 'fullcalendar/calendar_member.js'%}></script>
{% else %}
  <script src={%static 'fullcalendar/calendar_non_member.js'%}></script>
{% endif %}
-->
<script type="text/javascript">

$(document).ready(function() {
    $('#tournaments-table').DataTable({
      "bLengthChange": false ,"dom":'<"H"lr>ft<"F"ip>',
      "columnDefs": [ {
        targets: [1,2],
        render: $.fn.dataTable.render.moment( 'YYYY-MM-DD','L', '{{LANGUAGE_CODE}}' )
      } ],
      "order": [[ 1, "desc" ]]
    });

    $('#leagues-table').DataTable({
      "bLengthChange": false ,"dom":'<"H"lr>ft<"F"ip>',
      "columnDefs": [ {
        targets: [1,2],
        render: $.fn.dataTable.render.moment( 'YYYY-MM-DD','L', '{{LANGUAGE_CODE}}' )
      } ],
      "order": [[ 1, "desc" ]]
    });

    var memberTable = $('#members-table').DataTable({
      "bAutoWidth": false,
      {% if admin %}
    "columnDefs": [
            {
                "targets": [ 3 ],
                "visible": false,
            },
            {
                "targets": [ 4 ],
                "visible": false
            },
            {
                "targets": [ 5 ],
                "visible": false,
            },]
      {% endif %}
          }
    )
    {% if admin %}
    $('#cal-event-table').DataTable({
      "bLengthChange": false ,"dom":'<"H"lr>ft<"F"ip>',
      "columnDefs": [ {
        targets: 1,
        render: $.fn.dataTable.render.moment( 'MMM DD, YYYY HH:mm','MMM DD, YYYY HH:mm' )
      } ],
      "order": [[ 1, "desc" ]]
    });

    $('.toggle-column').on( 'click', function (e) {

        // Get the column API object
        var column = memberTable.column( $(this).attr('data-column') );

        // Toggle the visibility
        column.visible( ! column.visible() );
    } );
    {% endif %}

});
</script>
{{ calendar_data|json_script:"context-data" }}
<script>{% include 'league/includes/ajax_setup.html' %}</script>
<script src={% static 'fullcalendar/calendar.js' %}></script>
<script>
	$(document).ready(function() {
    Calendar.initialize('{{LANGUAGE_CODE}}');
  });
</script>
{% endblock %}