league/urls.py
import re

from django.conf.urls import url

from league.models import LeagueEvent

from . import views

# init urlpatterns
urlpatterns = []

# make the pattern for all the events
for (event_type, _) in LeagueEvent.EVENT_TYPE_CHOICES:
    new_pattern = [url(r'^' + re.escape(event_type) + r'/$',
                       views.get_first_league_event(event_type), name=event_type)]
    urlpatterns = urlpatterns + new_pattern

app_name = 'league'
urlpatterns = urlpatterns + [
    url(r'^$', views.division_results, name='results'),
    # Sad, but for historical reason, info page is named event.
    # If you want to replace reverses everywhere, be my guest
    url(r'^infos/$', views.infos, name='event'),
    url(r'^9x9/$', views.ninenine, name='ninenine'),

    url(r'^results/$', views.division_results, name='results'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/$',
        views.populate, name='admin_event_populate'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/(?P<from_event_id>[0-9]+)/$',
        views.populate, name='admin_event_populate'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/proceed-populate/(?P<from_event_id>[0-9]+)/$',
        views.proceed_populate, name='admin_proceed_populate'),
    url(r'^archives/$', views.archives, name='archives'),

    url(r'^(?P<event_id>[0-9]+)/results/(?P<division_id>[0-9]+)/$',
        views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/results/$',
        views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/infos/$', views.infos, name='event'),
    url(r'^(?P<event_id>[0-9]+)/iframe/$',
        views.division_results_iframe, name='results_iframe'),
    url(r'^(?P<event_id>[0-9]+)/iframe/(?P<division_id>[0-9]+)/$',
        views.division_results_iframe, name='results_iframe'),

    url(r'^games/$', views.list_games, name='games'),
    url(r'^games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),
    url(r'^(?P<event_id>[0-9]+)/games/$', views.list_games, name='games'),
    url(r'^(?P<event_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)/$',
        views.list_games, name='game'),

    url(r'^players/$', views.list_players, name='players'),
    url(r'^(?P<event_id>[0-9]+)/players/$',
        views.list_players, name='players'),

    url(r'^discord/$', views.discord_redirect, name='discord_redirect'),

    url(r'^sgf/(?P<sgf_id>[0-9]+)/$', views.download_sgf, name='sgf'),
    url(r'^all_sgf/(?P<user_id>[0-9]+)/$',
        views.download_all_sgf, name='all_sgf'),

    url(r'^account/timezone/$', views.timezone_update, name='timezone_update'),


    url(r'^account/$', views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/$',
        views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/activity/$',
        views.account_activity, name='league_account_activity'),
    url(r'^scraper/$', views.scraper_view, name='scraper'),

    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/$',
        views.admin_edit_sgf, name='edit_sgf'),
    url(r'^admin/handle-upload-sgf/$',
        views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/handle-upload-sgf/(?P<tournament_id>[0-9]+)/$',
        views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/upload-sgf/$', views.upload_sgf, name='upload_sgf'),
    url(r'^admin/create-sgf/$', views.create_sgf, name='create_sgf'),

    url(r'^admin/events/$', views.admin_events, name='admin_events'),
    url(
        r'^admin/events/(?P<pk>[0-9]+)/$',
        views.LeagueEventUpdate.as_view(),
        name='admin_events_update',
    ),
    url(
        r'^admin/events/create/$',
        views.LeagueEventCreate.as_view(success_url='/league/admin/events/'),
        name='admin_events_create',
    ),
    url(
        r'^admin/events/create/(?P<copy_from_pk>[0-9]+)/$',
        views.LeagueEventCreate.as_view(),
        name='admin_events_create',
    ),
    url(r'^admin/events/(?P<event_id>[0-9]+)/set_primary/$',
        views.admin_events_set_primary, name='set_primary'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/delete/$',
        views.admin_events_delete, name='delete_event'),
    url(r'^admin/sgf/$', views.admin_sgf_list, name='admin_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/save/$',
        views.admin_save_sgf, name='save_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/delete/$',
        views.admin_delete_sgf, name='delete_sgf'),
    url(r'^division/(?P<pk>[0-9]+)/informations/$',
        views.DivisionUpdate.as_view(), name='division_update_infos'),
    url(r'^division/(?P<division_id>[0-9]+)/forfeit/create$',
        views.division_create_forfeit, name='division_create_forfeit'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/$',
        views.division_update_wont_play, name='division_update_wont_play'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/create$',
        views.division_create_wont_play, name='division_create_wont_play'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/remove$',
        views.division_remove_wont_play, name='division_remove_wont_play'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/create-division/$',
        views.admin_create_division, name='admin_create_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/delete-division/$',
        views.admin_delete_division, name='admin_delete_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/rename/$',
        views.admin_rename_division, name='admin_rename_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/winner/$',
        views.division_set_winner, name='division_set_winner'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/up-down/$',
        views.admin_division_up_down, name='admin_division_up_down'),
    url(r'^admin/users/$', views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/division/(?P<division_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/(?P<user_id>[0-9]+)/send-mail/$',
        views.admin_user_send_mail, name='admin_user_send_mail'),
    url(r'^scrap-list/$', views.scrap_list, name='scrap_list'),
    url(r'^scrap-list/(?P<profile_id>[0-9]+)/up/$',
        views.scrap_list_up, name='scrap_list_up'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/$', views.game_api, name='game_api'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/(?P<event_id>[0-9]+)/$',
        views.game_api, name='game_api'),

    url(r'^(?P<event_id>[0-9]+)/join/(?P<user_id>[0-9]+)/$',
        views.join_event, name='join_event'),
    url(r'^(?P<event_id>[0-9]+)/quit/$',
        views.quit_league, name='quit_league'),
    url(r'^(?P<event_id>[0-9]+)/quit/(?P<user_id>[0-9]+)/$',
        views.quit_league, name='quit_league'),

    url(r'^admin/create-profile/(?P<user_id>[0-9]+)$',
        views.create_profile, name='create_profile'),
    url(r'^admin/update-all-sgf-check-code/$',
        views.update_all_sgf_check_code, name='update_all_sgf_check_code'),
    url(
        r'^admin/update_all_profiles/$',
        views.update_all_profiles,
        name='update_all_profiles',
    ),
    url(r'^admin/set-meijin/$', views.admin_set_meijin, name='set_meijin'),
    url(r'^admin/download-ffg-tou/(?P<league_id>[0-9]+)/$',
        views.download_ffg_tou, name='download_ffg_tou'),
    url(
        r'^profile/update/$',
        views.ProfileUpdate.as_view(),
        name='profile_update',
    ),
    url(
        r'^profile/(?P<pk>[0-9]+)/update/$',
        views.ProfileUpdate.as_view(),
        name='profile_update',
    ),
    url(r'discord-api/$', views.discord_api, name='discord_api'),
    url(r'games-api/$', views.games_datatable_api, name='games_api'),
    url(r'user-leagues-manage/(?P<user_id>[0-9]+)/$',
        views.user_leagues_manage, name='user_leagues_manage'),
    url(r'random-game/$', views.random_game, name='random_game'),
]

wgo/urls.py
from django.conf.urls import url

from . import views

app_name = 'wgo'


urlpatterns = [
    url(
        r'^tsumego-api/$',
        views.tsumego_api,
        name='tsumego_api',
    ),
]

league/templates/league/admin/create_forfeit.html
{% extends 'full_width.html' %}
{% load bootstrap3 league_tags i18n %}
{% block title %} {{division.name}} edit {% endblock %}
{% block heading %}
<div class="page-header">
    <h1> {% blocktrans with division_name=division.name %}{{division_name}} - create forfeit{% endblocktrans %}</h1>
    <a href="{% url 'league:results' event_pk division.pk %}">{% trans "Go back to division's page" %}</a>
</div>
{%endblock%}

{% block content %}
<div class="row">
    <div class="col-md-2">
        <form action="{% url 'league:division_create_forfeit' division.pk %}" method="POST">{% csrf_token %}
            <div class="form-group">
                <select id="select-winner" class="form-control" name="winner">
                    <option value="">{% trans "Select the winner" %} ...</option>
                    {% for player in division.get_results %}
                        <option value="{{player.user.pk}}">{{player.user}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <select id="select-loser" class="form-control" name="loser">
                    <option value="">{% trans "Select the loser" %} ...</option>
                    {% for player in division.get_results %}
                        <option value="{{player.user.pk}}">{{player.user}}</option>
                    {% endfor %}
                </select>
            </div>
            <button id="button_submit" class="btn btn-primary" type="submit" disabled>{% trans "Create SGF" %}</button>
        </form>
    </div>
</div>

{% endblock %}
{% block extra_css %}
{% endblock extra_css %}

{% block extra_js %}
{{ form.media.js }}
<script>
    const winner = document.getElementById('select-winner')
    const loser = document.getElementById('select-loser')
    function onSelectChange(e) {
        const submit = document.getElementById('button_submit')
        if (winner.value && loser.value && winner.value != loser.value)
            submit.removeAttribute('disabled')
        else
            submit.setAttribute('disabled', true)
    }
    winner.addEventListener('change', onSelectChange)
    loser.addEventListener('change', onSelectChange)

</script>
{% endblock extra_js %}

league/templates/league/admin/event_edit.html
{{ edit_event.name }}

league/templates/league/admin/event_list.html
{% load community_tags l10n i18n %}
{% localize off %}
{% language 'en' %}
<table id='leagues-table' class='display table' cellspacing='0' width='100%' >
	<thead>
		<th>{% trans "Status" %}</th>
		{% comment %}Translators : public (league) {% endcomment %}
		<th>{% trans "Public?" %}</th>
		<th>{% trans "Name" %}</th>
		<th>{% trans "Begin" %}</th>
		<th>{% trans "End" %}</th>
    <th>{% trans "Community" %}</th>
		<th>{% trans "Players" %}</th>
		<th>{% trans "#Divisions" %}</th>
		<th>{% trans "#Games" %}</th>
		<th>{% trans "ppw" %}</th>
		<th>{% trans "ppl" %}</th>
		<th>{% trans "min match" %}</th>
    <th>{% trans "copy" %}</th>
	</thead>
	<tbody>
	{% for event in events %}
	<tr {% if event.community is not None%} class="info"{% endif %}>
		{% comment %}Translators : OPEN / CLOSED (league) {% endcomment %}
		<td> {% if event.is_open %} <b>{% trans "Open" %}</b> {% else %} {% trans "Closed" %} {% endif %}</td>
		{% comment %}Translators : PUBLIC / PRIVATE (league) {% endcomment %}
		<td>{% if event.is_public %} {% trans "Public" %} {% else %} {% trans "Private" %} {% endif %}</td>
		<td> <a href= "{% url 'league:admin_events_update' event.pk %}"> {{ event.name }} </a> </td>
		<td> {{ event.begin_time | date:"M d, Y" }}  </td>
		<td> {{ event.end_time | date:"M d, Y" }} </td>
    <td>{{ event.community | community_link }}</td>
		<td><a href="{% url 'league:admin_users_list' event.pk %}">	{{ event.number_players }} </a></td>
		<td> {{ event.number_divisions }}</td>
		<td> {{ event.number_games }} </td>
		<td> {{ event.ppwin }} </td>
		<td> {{ event.pploss }} </td>
		<td> {{ event.min_matchs }} </td>
    <td> <a href= "{% url 'league:admin_events_create' event.pk %}"> <i class="fa fa-copy"></i> </a> </td

	</tr>
	{% endfor %}
	</tbody>
</table>

{% endlanguage %}

{% endlocalize %}

league/templates/league/admin/populate.html
{% extends "full_width.html" %}
{% load bootstrap3 league_tags i18n %}
{% block title %}{% trans "OSR league admin" %}{% endblock %}
{% block content %}
<form  method="post" class="form">
    {% csrf_token %}
<div class='row'>
  <div class="panel panel-default">
  <div class="panel-heading"><h4>{% trans "Rollover overview" %}"/h4></div>
  <div class="panel-body">
    <div class='col-md-8'>
    <p>{% blocktrans with to_event=to_event from_event=from_event %}You are populating <b>{{to_event}}</b> with players from <b>{{from_event}}</b> {% endblocktrans %}</p>
    <p>{% blocktrans with from_event_number_players=from_event.number_players from_event_number_actives_players=from_event.number_actives_players from_event_number_inactives_players=from_event.number_inactives_players %}Out of {{from_event_number_players}} players, {{from_event_number_actives_players}} were active and {{from_event_number_inactives_players}} will get drop.{% endblocktrans %}</p>
    <p>{% blocktrans with from_event_min_matchs=from_event.min_matchs %} The minimum number of games to stay in the league is set to <b>{{from_event_min_matchs}}</b>.{% endblocktrans %}<p>   
    </div>
    <div class='col-md-2'>
      <button type="submit" class="btn btn-info" formaction="{% url 'league:admin_event_populate' to_event.pk from_event.pk%}" >
    {% bootstrap_icon "refresh" %}  {% trans "Preview" %}
  </button>
    </div>
    <div class='col-md-2'>
      {%if preview%}
    <button type="submit" class="btn btn-success" formaction="{% url 'league:admin_proceed_populate' to_event.pk from_event.pk  %}"onclick="return confirm('Populate the new {{to_event}} with above players ?')" >
      {% bootstrap_icon "ok" %}  {% trans "Save" %}
    </button>
    {%endif%}
  </div>
</div>
  </div>
</div>


<div class='row'>

  <div class='col-md-6'>
    <legend> {{from_event}} </legend>

  {% for division in divisions %}
  <div class="panel panel-default clearfix">
  <div class="panel-heading">{{division.name}}
    <div class="pull-right"> {{division.number_players}} players | {{division.number_games}} {% trans "games" %}</div>
  </div>
  <div class="panel-body">

    <table class='table table-condensed'  >
       <thead>
         <tr>
           <th>{% trans "Rank" %}</th>
           <th>{% trans "Player" %}</th>
           <th>{% trans "Score" %}</th>
           <th>{% trans "Games" %}</th>
           <th>{% trans "Next" %}</th>
        </tr>
      </thead>

      <tbody>

  {% for player in division.results %}
      <tr {% if player.is_active %} class= "danger"{% endif %}>
        <td>{{forloop.counter}}</td>
        <td>{{player.user |user_link}}</td>
        <td>{{player.score}}</td>
        <td>{{player.n_games}}</td>
        <td>{% if player.is_active %}  {{form |player_field:player.pk }} {% endif %}</td>
      </tr>


  {% endfor %}

  </tbody>
</table>

  </div>
  </div>

  {% endfor %}

</div>


<div class ='col-md-6'>
  <legend> {{to_event}} {% trans "preview" %} </legend>
  {%  for division, players in new_players.items %}
  <div class="panel panel-default">
  <div class="panel-heading clearfix">{{division}}
    <div class="pull-right"> {{players|length}} players</div>
  </div>
  <div class="panel-body">
  <table class='table table-condensed'  >
     <thead>
       <tr>
         <th>{% trans "Player" %}</th>
         <th>{% trans "Previous division" %}</th>
      </tr>
    </thead>

    <tbody>
      {% for player in players %}
        <tr>
            <td>{{player.user |user_link}}</td>
            <td>{{player.previous_division.name}}</td>
          </tr>


      {% endfor %}

      </tbody>
    </table>
</div>
</div>
{% endfor %}
</div>

</div>
</form>
{% endblock %}

league/templates/league/admin/sgf_edit.html
{% extends "league/admin/base.html" %}
{% load bootstrap3 wgo_tags league_tags l10n i18n %}
{% block title %}Edit a sgf{% endblock %}

{% block heading %}
<div class="page-header">
    <h1>{% blocktrans with sgf_wplayer=sgf.wplayer sgf_bplayer=sgf.bplayer sgf_date=sgf.date |date:"M d, Y" %}{{sgf_wplayer}} vs {{sgf_bplayer}} the {{sgf_date}}{% endblocktrans %}</h1>
</div>
{%endblock%}
{% block content %}

<div class="row">
  <div class="col-md-4">
    <p>
    <button form="sgf-form" type="submit" class="btn btn-info " formaction="{%url 'league:edit_sgf' sgf.pk%}" >
      {% bootstrap_icon "refresh" %}  {% trans "Check sgf" %}
    </button>
  </p>
  </div>
  <div class="col-md-4">
    <form  method="post" class="form">
    {% csrf_token %}
    <input type="hidden" name="action" value="delete_sgf">
    <button form="sgf-form" type="submit" class="btn btn-danger " formaction="{%url 'league:delete_sgf' sgf.pk%}" onclick="return confirm('Are you sure you want to delete this SGF ?')" >
      {% bootstrap_icon "remove" %}  {% trans "Delete SGF" %}
    </button>
    </form>
    </div>
</div>
{% if preview %}
<div class="row">
<div class="alert alert-info" role="alert">{% trans "This is a preview of your changes. Click " %}<button form="sgf-form" type="submit" class="btn btn-success btn-xs" formaction="{%url 'league:save_sgf' sgf.pk%}"onclick="return confirm('Save the sgf to db ?')" >
  {% bootstrap_icon "ok" %} {% trans "Save sgf" %}
</button> {% trans "to save them to the database." %}</div>
</div>
{% endif %}
<div class="row">

   <div class="col-md-3">
     <div class="panel panel-default">
       <div class="panel-heading"> Sgf infos</div>
     <table class="table table-condensed">
    <tbody>
      <tr>
        <th>ID</th>
        <td> {{sgf.pk}}</td>
      </tr>
        <tr>
          <th>{% trans "White" %}</th>
            <td>{{sgf.wplayer}}</td>
        </tr>
        <tr>
          <th>{% trans "Black" %}</th>
            <td>{{sgf.bplayer}}</td>
        </tr>
        <tr>
          <th>{% trans "Date" %}</th>
          <td> {{sgf.date |date:"M d, Y"}}</td>
        </tr>
        <tr>
          <th>{% trans "Result" %}</th>
          <td> {{sgf.result}}</td>
        </tr>
        <tr>
          <th>{% trans "Type" %}</th>
          <td> {{sgf.game_type}}</td>
        </tr>
        <tr>
          <th>{% trans "p_status" %}</th>
          <td> {{sgf.p_status | p_status}}</td>
        </tr>
        <tr>
          <th>{% trans "Download" %} </th>
          <td>   <a href="{% url 'league:sgf' sgf.pk%}">{% bootstrap_icon 'save' %} </a></td>
        </tr>


      </tbody>
    </table>
</div>

{% include 'league/includes/sgf_errors.html' %}

</div>





<div class="col-md-4">
  <form id="sgf-form"  method="post" class="form">
  {% csrf_token %}
    {% bootstrap_form form %}

  </form>




</div>
<div class="col-md-5">
  <div data-wgo="{{ sgf.sgf_text  | prepare_sgf}}">
</div>
</div>
</div>

{% endblock %}

league/templates/league/admin/sgf_list.html
{% extends 'league/admin/base.html' %}
{% load bootstrap3 league_tags l10n i18n %}
{% block heading %}
<div class="page-header">
    <h1>{% trans "All sgfs" %}"/h1>
</div>
{%endblock%}

{% block content %}
<div class="panel panel-default">
  <div class="panel-heading">
    {% trans "Upload a sgf" %}
  </div>
  <div class="panel-body">
    <form enctype="multipart/form-data" class="form-inline"action=" {% url 'league:handle_upload_sgf' %}" method="post" class="form">
  {% csrf_token %}
  <div class="form-group"><label class="sr-only" for="id_file">File</label><div class="row bootstrap3-multi-input"><div class="col-xs-12"><input class="" id="id_file" name="file" title="" type="file" required /></div></div></div>
  <button type="submit" class="btn btn-success btn-sm" >
    {% bootstrap_icon "ok" %}  {% trans "Submit" %}
  </button>
  </form>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    {% trans "List of all OSR sgfs" %}
  </div>
<table id='sgf-table' class='table table-over' >
  <thead>
    <th>Id</th>
    <th> {% trans "Date" %}</th>
    <th> {% trans "White" %}</th>
    <th>{% trans "Black" %}</th>
    <th>{% trans "Result" %}</th>
    <th> {% trans "Type" %} </th>
    <th>{% trans "League valid?" %}</th>
    <th>{% trans "p_status" %}</th>
    <th>{% trans "Edit" %}</th>
  </thead>
</tbody>
{% for sgf in sgfs%}
<tr>
<td>{{sgf.pk}}</td>
<td>{{sgf.date | date:"M d, Y"}}</td>
<td>{{sgf.wplayer}}</td>
<td>{{sgf.bplayer}}</td>
<td>{{sgf.result}}</td>
<td>{{sgf.game_type}}</td>
<td>{{sgf.league_valid | boolean_icon}}</td>
<td>{{sgf.p_status}}</td>
<td><a href= "{% url 'league:edit_sgf' sgf.pk %}"> <span class="glyphicon glyphicon-menu-right"></span></a></td>

</tr>
  {% endfor %}
</tbody>
</table>
</div>
</div>

{% endblock %}

{% block extra_js %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#sgf-table').DataTable({"order": [[ 0, "desc" ]]});
} );
</script>
{% endblock %}

league/templates/league/admin/update_all_profiles.html
{% extends "full_width.html" %}
{% load wagtailcore_tags i18n %}
{% load league_tags %}
{% load bootstrap3 %}

{% block body_class %}user{% endblock %}

{% block title %}{% trans "Update all sgfs check code" %}{% endblock %}
{% block heading %}
<div class="page-header">
    <h1>{% trans "Update all sgfs check code" %}</h1>
</div>
{%endblock%}
{% block content %}
<div class="row">
  <div class="jumbotron">
<p>{% trans "Dear admin," %}</p>
<p>{% trans "Please pay attention to this message and don't proceed before reading." %}</p>
<p>{% trans "In this page, can update some profiles datas." %}</p>
<p>{% trans "If you don't understand what this is about, you should just leave this page." %}</p>
<p>{% trans "If you have any doubt what so ever about wether you should continue or not, you should leave this page." %}</p>
<p>{% trans "If you just did read the code of views.update_all_profiles and understand what you are doing, you may proceed." %}</p>
  </div>
  <div class="col-md-4">
    <a href="{% url 'league:admin' %}"class="btn btn-primary text-left">Back to admin</a>
  </div>
  <div class="col-md-4">
  <form action=" {% url 'league:update_all_profiles'  %}" method="post" class="form">
{% csrf_token %}
<input type="hidden" name="action" value="update_all_profiles">
<button type="submit" class="btn btn-danger"  onclick="return confirm('Are you positively sure you want to update things in profiles ?')">

{% bootstrap_icon "warning-sign" %} {% trans "No fear, I do it!" %}
</button>

</form>
</div>
{% endblock %}

league/templates/league/admin/update_all_sgf_check_code.html
{% extends "full_width.html" %}
{% load wagtailcore_tags i18n %}
{% load league_tags %}
{% load bootstrap3 %}

{% block body_class %}user{% endblock %}

{% block title %}{% trans "Update all sgfs check code" %}{% endblock %}
{% block heading %}
<div class="page-header">
    <h1>{% trans "Update all sgfs check code" %}</h1>
</div>
{%endblock%}
{% block content %}
<div class="row">
  <div class="jumbotron">
<p>{% trans "Dear admin," %</p>
<p>{% trans "Please pay attention to this message and don't proceed before reading." %</p>
<p>{% trans "In this page, you can rescan all sgf in our db and update their check_code." %</p>
<p>{% trans "If you don't understand what this is about, you should just leave this page." %</p>
<p>{% trans "If you have any doubt what so ever about wether you should continue or not, you should leave this page." %</p>
<p>{% trans "If you just changed our check_code and positively want to update all sgf check code, you may proceed." %</p>
  </div>
  <div class="col-md-4">
    <a href="{% url 'league:admin' %}"class="btn btn-primary text-left">{% trans "Back to admin" %</a>
  </div>
  <div class="col-md-4">
  <form action=" {% url 'league:update_all_sgf_check_code'  %}" method="post" class="form">
{% csrf_token %}
<input type="hidden" name="action" value="update_all_sgf">
<button type="submit" class="btn btn-danger"  onclick="return confirm('Are you positively sure you want to reparse all sgf in db and update their fields ?')">

{% bootstrap_icon "warning-sign" %} {% trans "No fear, I do it!" %}"
</button>

</form>
</div>
{% endblock %}