league/urls.py
import re

from django.conf.urls import url

from league.models import LeagueEvent

from . import views

# init urlpatterns
urlpatterns = []

# make the pattern for all the events
for (event_type, _) in LeagueEvent.EVENT_TYPE_CHOICES:
    new_pattern = [url(r'^' + re.escape(event_type) + r'/$',
                       views.get_first_league_event(event_type), name=event_type)]
    urlpatterns = urlpatterns + new_pattern

app_name = 'league'
urlpatterns = urlpatterns + [
    url(r'^$', views.division_results, name='results'),
    # Sad, but for historical reason, info page is named event.
    # If you want to replace reverses everywhere, be my guest
    url(r'^infos/$', views.infos, name='event'),
    url(r'^9x9/$', views.ninenine, name='ninenine'),

    url(r'^results/$', views.division_results, name='results'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/$',
        views.populate, name='admin_event_populate'),
    url(r'^admin/event/(?P<to_event_id>[0-9]+)/populate/(?P<from_event_id>[0-9]+)/$',
        views.populate, name='admin_event_populate'),

    url(r'^admin/event/(?P<to_event_id>[0-9]+)/proceed-populate/(?P<from_event_id>[0-9]+)/$',
        views.proceed_populate, name='admin_proceed_populate'),
    url(r'^archives/$', views.archives, name='archives'),

    url(r'^(?P<event_id>[0-9]+)/results/(?P<division_id>[0-9]+)/$',
        views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/results/$',
        views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/$', views.division_results, name='results'),
    url(r'^(?P<event_id>[0-9]+)/infos/$', views.infos, name='event'),
    url(r'^(?P<event_id>[0-9]+)/iframe/$',
        views.division_results_iframe, name='results_iframe'),
    url(r'^(?P<event_id>[0-9]+)/iframe/(?P<division_id>[0-9]+)/$',
        views.division_results_iframe, name='results_iframe'),

    url(r'^games/$', views.list_games, name='games'),
    url(r'^games/(?P<sgf_id>[0-9]+)/$', views.list_games, name='game'),
    url(r'^(?P<event_id>[0-9]+)/games/$', views.list_games, name='games'),
    url(r'^(?P<event_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)/$',
        views.list_games, name='game'),

    url(r'^players/$', views.list_players, name='players'),
    url(r'^(?P<event_id>[0-9]+)/players/$',
        views.list_players, name='players'),

    url(r'^discord/$', views.discord_redirect, name='discord_redirect'),

    url(r'^sgf/(?P<sgf_id>[0-9]+)/$', views.download_sgf, name='sgf'),
    url(r'^all_sgf/(?P<user_id>[0-9]+)/$',
        views.download_all_sgf, name='all_sgf'),

    url(r'^account/timezone/$', views.timezone_update, name='timezone_update'),


    url(r'^account/$', views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/$',
        views.account, name='league_account'),
    url(r'^account/(?P<user_name>[\w.@+-]+)/activity/$',
        views.account_activity, name='league_account_activity'),
    url(r'^scraper/$', views.scraper_view, name='scraper'),

    url(r'^admin/$', views.admin, name='admin'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/$',
        views.admin_edit_sgf, name='edit_sgf'),
    url(r'^admin/handle-upload-sgf/$',
        views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/handle-upload-sgf/(?P<tournament_id>[0-9]+)/$',
        views.handle_upload_sgf, name='handle_upload_sgf'),
    url(r'^admin/upload-sgf/$', views.upload_sgf, name='upload_sgf'),
    url(r'^admin/create-sgf/$', views.create_sgf, name='create_sgf'),

    url(r'^admin/events/$', views.admin_events, name='admin_events'),
    url(
        r'^admin/events/(?P<pk>[0-9]+)/$',
        views.LeagueEventUpdate.as_view(),
        name='admin_events_update',
    ),
    url(
        r'^admin/events/create/$',
        views.LeagueEventCreate.as_view(success_url='/league/admin/events/'),
        name='admin_events_create',
    ),
    url(
        r'^admin/events/create/(?P<copy_from_pk>[0-9]+)/$',
        views.LeagueEventCreate.as_view(),
        name='admin_events_create',
    ),
    url(r'^admin/events/(?P<event_id>[0-9]+)/set_primary/$',
        views.admin_events_set_primary, name='set_primary'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/delete/$',
        views.admin_events_delete, name='delete_event'),
    url(r'^admin/sgf/$', views.admin_sgf_list, name='admin_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/save/$',
        views.admin_save_sgf, name='save_sgf'),
    url(r'^admin/sgf/(?P<sgf_id>[0-9]+)/delete/$',
        views.admin_delete_sgf, name='delete_sgf'),
    url(r'^division/(?P<pk>[0-9]+)/informations/$',
        views.DivisionUpdate.as_view(), name='division_update_infos'),
    url(r'^division/(?P<division_id>[0-9]+)/forfeit/create$',
        views.division_create_forfeit, name='division_create_forfeit'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/$',
        views.division_update_wont_play, name='division_update_wont_play'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/create$',
        views.division_create_wont_play, name='division_create_wont_play'),
    url(r'^division/(?P<division_id>[0-9]+)/wont-play/remove$',
        views.division_remove_wont_play, name='division_remove_wont_play'),
    url(r'^admin/events/(?P<event_id>[0-9]+)/create-division/$',
        views.admin_create_division, name='admin_create_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/delete-division/$',
        views.admin_delete_division, name='admin_delete_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/rename/$',
        views.admin_rename_division, name='admin_rename_division'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/winner/$',
        views.division_set_winner, name='division_set_winner'),
    url(r'^admin/division/(?P<division_id>[0-9]+)/up-down/$',
        views.admin_division_up_down, name='admin_division_up_down'),
    url(r'^admin/users/$', views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/event/(?P<event_id>[0-9]+)/division/(?P<division_id>[0-9]+)/$',
        views.admin_users_list, name='admin_users_list'),
    url(r'^admin/users/(?P<user_id>[0-9]+)/send-mail/$',
        views.admin_user_send_mail, name='admin_user_send_mail'),
    url(r'^scrap-list/$', views.scrap_list, name='scrap_list'),
    url(r'^scrap-list/(?P<profile_id>[0-9]+)/up/$',
        views.scrap_list_up, name='scrap_list_up'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/$', views.game_api, name='game_api'),
    url(r'^game/json/(?P<sgf_id>[0-9]+)/(?P<event_id>[0-9]+)/$',
        views.game_api, name='game_api'),

    url(r'^(?P<event_id>[0-9]+)/join/(?P<user_id>[0-9]+)/$',
        views.join_event, name='join_event'),
    url(r'^(?P<event_id>[0-9]+)/quit/$',
        views.quit_league, name='quit_league'),
    url(r'^(?P<event_id>[0-9]+)/quit/(?P<user_id>[0-9]+)/$',
        views.quit_league, name='quit_league'),

    url(r'^admin/create-profile/(?P<user_id>[0-9]+)$',
        views.create_profile, name='create_profile'),
    url(r'^admin/update-all-sgf-check-code/$',
        views.update_all_sgf_check_code, name='update_all_sgf_check_code'),
    url(
        r'^admin/update_all_profiles/$',
        views.update_all_profiles,
        name='update_all_profiles',
    ),
    url(r'^admin/set-meijin/$', views.admin_set_meijin, name='set_meijin'),
    url(r'^admin/download-ffg-tou/(?P<league_id>[0-9]+)/$',
        views.download_ffg_tou, name='download_ffg_tou'),
    url(
        r'^profile/update/$',
        views.ProfileUpdate.as_view(),
        name='profile_update',
    ),
    url(
        r'^profile/(?P<pk>[0-9]+)/update/$',
        views.ProfileUpdate.as_view(),
        name='profile_update',
    ),
    url(r'discord-api/$', views.discord_api, name='discord_api'),
    url(r'games-api/$', views.games_datatable_api, name='games_api'),
    url(r'user-leagues-manage/(?P<user_id>[0-9]+)/$',
        views.user_leagues_manage, name='user_leagues_manage'),
    url(r'random-game/$', views.random_game, name='random_game'),
]

tournament/urls.py
from django.conf.urls import url

from . import views

app_name = 'tournament'

urlpatterns = [
    url(
        r'^(?P<tournament_id>[0-9]+)/$',
        views.about,
        name='view',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/rules/$',
        views.rules,
        name='rules',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/prizes/$',
        views.prizes,
        name='prizes',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/about/$',
        views.about,
        name='about',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/groups/$',
        views.groups_view,
        name='groups',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/$',
        views.calendar,
        name='calendar',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar-feed/$',
        views.calendar_feed,
        name='calendar_feed',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/new-event/$',
        views.create_calendar_event,
        name='create_calendar_event',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/about/edit/$',
        views.edit_about,
        name='edit_about',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/games/$',
        views.games_view,
        name='games',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/games/(?P<sgf_id>[0-9]+)$',
        views.games_view,
        name='games',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/brackets/$',
        views.brackets_view,
        name='brackets',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/players/$',
        views.players_view,
        name='players',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/profile/(?P<user_id>[0-9]+)/update/$',
        views.edit_player_profile,
        name='edit_player_profile',
    ),
    url(
        r'^create/$',
        views.TournamentCreate.as_view(success_url='/tournament/list/'),
        name='create',
    ),
    url(
        r'^list/$',
        views.tournament_list,
        name='list',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/calendar/manage/$',
        views.manage_calendar,
        name='manage_calendar',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/settings/$',
        views.manage_settings,
        name='manage_settings',
    ),

    url(
        r'^(?P<tournament_id>[0-9]+)/admin/groups/$',
        views.manage_groups,
        name='manage_groups',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/brackets/$',
        views.manage_brackets,
        name='manage_brackets',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/games/$',
        views.manage_games,
        name='manage_games',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/upload_sgf/$',
        views.upload_sgf,
        name='upload_sgf',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/create-sgf/$',
        views.create_sgf,
        name='create_sgf',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/set-stage/$',
        views.set_stage,
        name='set_stage',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/invite/$',
        views.invite_user,
        name='invite_user',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/admin/quit/$',
        views.remove_players,
        name='remove_players',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save_players_order/$',
        views.save_players_order,
        name='save_players_order',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/create-group/$',
        views.create_group,
        name='create_group',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/create-bracket/$',
        views.create_bracket,
        name='create_bracket',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save-groups/$',
        views.save_groups,
        name='save_groups',
    ),
    url(
        r'^create-match/(?P<round_id>[0-9]+)/$',
        views.create_match,
        name='create_match',
    ),
    url(
        r'^delete_match/(?P<round_id>[0-9]+)/$',
        views.delete_match,
        name='delete_match',
    ),
    url(
        r'^create-round/(?P<bracket_id>[0-9]+)/$',
        views.create_round,
        name='create_round',
    ),
    url(
        r'^rename-round/(?P<round_id>[0-9]+)/$',
        views.rename_round,
        name='rename_round',
    ),
    url(
        r'^delete-round/(?P<round_id>[0-9]+)/$',
        views.delete_round,
        name='delete_round',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/save-brackets/$',
        views.save_brackets,
        name='save_brackets',
    ),
    url(
        r'^rename-bracket/(?P<bracket_id>[0-9]+)/$',
        views.rename_bracket,
        name='rename_bracket',
    ),
    url(
        r'^delete-bracket/(?P<bracket_id>[0-9]+)/$',
        views.delete_bracket,
        name='delete_bracket',
    ),
    url(
        r'^update-event/(?P<pk>[0-9]+)/$',
        views.TournamentEventUpdate.as_view(),
        name='update_event',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/set-winner/$',
        views.set_winner,
        name='set_winner',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/forfeit_group/(?P<group_id>[0-9]+)/$',
        views.forfeit_group,
        name='forfeit_group',
    ),
    url(
        r'^(?P<tournament_id>[0-9]+)/forfeit_bracket/(?P<match_id>[0-9]+)/$',
        views.forfeit_bracket,
        name='forfeit_bracket',
    ),
]

wgo/urls.py
from django.conf.urls import url

from . import views

app_name = 'wgo'


urlpatterns = [
    url(
        r'^tsumego-api/$',
        views.tsumego_api,
        name='tsumego_api',
    ),
]

league/templates/league/admin.html
{% extends "league/admin/base.html" %}
{% load wagtailcore_tags bootstrap3 %}
{% block title %}OSR league admin{% endblock %}
{% block heading %}
<div class="page-header">
    <h1>Dashboard</h1>
</div>
{%endblock%}
{% block content %}
<iframe name="embed_readwrite" frameBorder="0" src="https://mensuel.framapad.org/p/1N0qTQCsk6?showControls=true&showChat=false&showLineNumbers=false&useMonospaceFont=false" width=600 height=400></iframe>
<div class="panel panel-default">
<div class="panel-heading"><h3> List of new users </h3></div>
<div class="panel-body">
  <table id='new_user-table' class='display table' >
    <thead>
      <tr><th>username</th><th>email</th><th>kgs_username</th><th>Delete</th><th>Accept</th>
      </thead>
      <tbody>
        {% for new_user in new_users %}
        <tr>
          <td>{{new_user.username}}</td>
          <td>{{new_user.email}}</td>
          <td><a href="https://www.gokgs.com/gameArchives.jsp?user={{new_user.kgs_username}}" target="_blank">{{new_user.kgs_username}}</a></td>
          <td>  <form action=" {% url 'league:admin' %}" method="post" class="form">
            {% csrf_token %}
            <input type="hidden" name="action" value="delete_new_user">
            <input type="hidden" name="user_id" value="{{new_user.pk}}">
              <button type="submit" class="btn btn-danger btn-xs" onclick="return confirm('You are about to delete the new user {{new_user.username}}. Allright?')" >
                {% bootstrap_icon "remove" %}  delete
              </button>
            </form>
          </td>
          <td><form action=" {% url 'league:admin' %}" method="post" class="form">
            {% csrf_token %}
            <input type="hidden" name="action" value="welcome_new_user">
            <input type="hidden" name="user_id" value="{{new_user.pk}}">
              <button type="submit" class="btn btn-success btn-xs" onclick="return confirm('Accept the new user  {{new_user.username}} as a league memeber ?')">
                {% bootstrap_icon "ok" %}  Accept
              </button></form></td>
        </tr>
        {% endfor %}
      </tbdoy>
  </table>
</div>
</div>
<div class="panel panel-default">
<div class="panel-heading clearfix"><h3 class=" pull-left"> List of Sgf that didn't pass the test </h3>
<div class="btn-group pull-right">
  <legent> Upload a sgf</legend>
  <form enctype="multipart/form-data" class="form-inline"action=" {% url 'league:handle_upload_sgf' %}" method="post" class="form">
{% csrf_token %}
{% bootstrap_form form layout='inline'%}
<button type="submit" class="btn btn-success btn-sm" >
  {% bootstrap_icon "ok" %}  Submit
</button>
</form></div>
</div>
<div class="panel-body">

<table id='sgf-table' class='display table' cellspacing='0' width='100%' >
   <thead>
     <tr><th>date</th><th>white</th><th>black</th><th>result</th><th>message</th><th>Edit</th>
     </thead>
     <tbody>
       {% for sgf in sgfs %}
       <tr>
         <td> {{sgf.date |date:"M d, Y"}} </td>
         <td> {{sgf.wplayer }}</td>
         <td> {{sgf.bplayer }}</td>
         <td> {{sgf.result}} </td>
         <td>{{sgf.message}}</td>
         <td><a href= "{% url 'league:edit_sgf' sgf.pk %}"> <span class="glyphicon glyphicon-menu-right"></span></a></td>
       </tr>
{% endfor %}
</tbody></table>
</div>
</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.13/fh-3.1.2/r-2.1.0/sc-1.4.2/datatables.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
$('#sgf-table').DataTable({"order": [[ 0, "desc" ]]});
} );
</script>
{% endblock %}

league/templates/league/archives_games.html
{% extends "league/base.html" %}
{% load league_tags wgo_tags l10n i18n static %}

{% block title %}{% trans "Archives" %} - {% trans "Games" %} {% if sgf %}- {{sgf.black.username}} vs {{sgf.white.username}} {%endif %}{% endblock %}
{% block extra_head_js %}
<script type="text/javascript">
  function load_game(sgf_id) {
    $.ajax({
      type: "GET",
      url: "/league/game/json/" + sgf_id,
      dataType: "json",
      success: processData,
      error: function(){ alert("failed"); }
    });

    function processData(data) {
      document.getElementById("game_infos").innerHTML = data.game_infos;
      var elem = document.getElementById("player");
      var player = new WGo.BasicPlayer(elem, {
        sgf: data.sgf,
      });
      window.history.pushState('page2', 'Title', data.permalink);
      document.getElementById("game-header").innerText = ' - ' + data.white + ' vs ' + data.black;
      document.title ='Archives - Games - '+ data.white + ' vs ' + data.black + ' - Open Study Room';
      $("[data-toggle=tooltip]").tooltip();
    };

    return false;
  };
</script>
{% endblock %}

{% block content %}
    <ul class="nav nav-tabs">
        <li class="active"><a href="{% url 'league:archives' %}">{% trans "Archives" %}</a></li>
        {% for ev in open_events %}
            <li>
                <a href="{% url 'league:games' ev.pk %}">
                    {% if ev.is_primary %}
                        <strong>
                    {% endif %}
                    {{ev.name}}
                    {% if ev.is_primary %}
                        </strong>
                    {% endif %}</a>
            </li>
        {% endfor %}
        <li class="pull-right"><a href="{% url 'league:scrap_list' %}">{% trans "Scrape list" %}</a></li>
    </ul>
    <nav class="navbar navbar-default">
        <ul class="nav navbar-nav navbar-left">
            <li><a href="{% url 'league:archives' %}">{% trans "Leagues" %}</a></li>
            <li><a href="{% url 'league:players'  %}">{% trans "Players" %}</a></li>
            <li class="active"><a href="{% url 'league:games'  %}">{% trans "Games" %}</a></li>
        </ul>
    </nav>
    {% include "league/includes/game_table_view.html" %}
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/league.css' %}"/>
<link rel="stylesheet" href="{% static 'league/css/archives_games.css' %}"/>
{% endblock %}
{% block extra_js %}
{% include "league/includes/sgrfs_datatable.html" with sgfs_data_json=sgfs_data_json %}
{% endblock %}

league/templates/league/archives_players.html
{% extends "league/base.html" %}
{% load league_tags i18n %}
{% block title %}{% trans "Archives" %}- {% trans "Players" %}{% endblock %}
{% block content %}
  <ul class="nav nav-tabs">
    <li class="active"><a href="{% url 'league:archives' %}">{% trans "Archives" %}</a></li>
    {% for ev in open_events %}
      <li>
        <a href ="{% url 'league:players' ev.pk %}">
          {% if ev.is_primary %}
            <strong>
          {% endif %}
          {{ev.name}}
          {% if ev.is_primary %}
          </strong>
          {% endif %}
        </a>
      </li>
    {% endfor %}
    <li class="pull-right"><a href="{% url 'league:scrap_list' %}">{% trans "Scrape list" %}</a></li>
  </ul>
  <nav class="navbar navbar-default">
  <ul class="nav navbar-nav navbar-left">
    <li><a href="{% url 'league:archives' %}">{% trans "Leagues" %}</a></li>
    <li class="active"><a href="{% url 'league:players'  %}">{% trans "Players" %}</a></li>
    <li><a href="{% url 'league:games' %}">{% trans "Games" %}</a></li>
  </ul>

  </nav>
  <div class="well"> {% trans "This table show all users of the Open Study Room since it's creation." %}</div>
  <table id='player-table' class=' table table-hover '  >
    <thead>
      <tr>
        <th>{% trans "Player" %}</th>
        <th># {% trans "Leagues" %}</th>
        <th># {% trans "Wins" %}</th>
        {% comment %}Translators: 'loss' is plural{% endcomment %}
        <th># {% trans "Loss" %}</th>
        <th># {% trans "Games" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for u in users %}
      <tr>
        <td>{{u | user_link}}</td>
        <td>{{u.nb_players}}</td>
        <td>{{u.n_win}}</td>
        <td>{{u.n_loss}}</td>
        <td>{{u.n_games}}</td>
    </tr>
     {% endfor %}
   </tbody>
 </table>

{% endblock %}

{% block extra_js %}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.css"/>
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/datatables.min.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $('#player-table').DataTable({
      language: {
        searchPlaceholder: "{% trans 'OSR/KGS/OGS username' %}"
      }
    });
  } );
</script>

{% endblock %}

league/templates/league/base.html
{% extends "full_width.html" %}
{% load static community_tags forum_markup_tags i18n %}
{% block heading%}
  <div class="page-header">
      <h1>{% if event.community %}{{event.community|community_link}}{%else%}OSR{%endif%} {% trans "League" %} - {%if event %}{{event}}{% else%}{% trans "Archives"%}{% endif %}<span id='game-header'>{%if game %} - {{game.black.kgs_username}} vs {{game.white.kgs_username}} {%endif%} </span></h1>
      {% if event.description %}{{event.description|safe|rendered}}{% endif %}
  </div>
  {%endblock%}
  {% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/league.css' %}"/>
  {% endblock %}

league/templates/league/division_update_form.html
{% extends 'full_width.html' %}
{% load bootstrap3 league_tags i18n %}

{% comment %}Translators: it's a title : division_name edit{% endcomment %}
{% block title %}{% blocktrans with division_name=object.name %} {{division_name}} edit {% endblocktrans %}{% endblock %}
{% block heading %}
<div class="page-header">
    <h1> Edit the {{object.name}} division from {{object.league_event.name}} league</h1>
    <h1> {% blocktrans with object_name=object.name object_league_event_name=object.league_event.name %}Edit the {{object_name}} division from {{object_league_event_name}} league{% endblocktrans %}</h1>
</div>
{%endblock%}
{% block content %}
<form action="" method="POST">{% csrf_token %}
{%bootstrap_form form %}
	{% bootstrap_button "Save" button_type="submit" button_class="btn-primary" %}
</form>

{% endblock %}
{% block extra_css %}
    {{ form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
{{ form.media.js }}
{% endblock extra_js %}

league/templates/league/games.html
{% extends "league/base.html" %}
{% load tz static league_tags wgo_tags bootstrap3 l10n i18n %}

{% block title %}{% if sgf %} {{sgf.black.username}} vs {{sgf.white.username}} {% else %}{{event}}- {% trans "Games" %}{% endif %}{% endblock %}
{% block extra_head_js %}
<script type="text/javascript">
function load_game(sgf_id) {
    $.ajax({
    type: "GET",
    url: "/league/game/json/" + sgf_id,
    dataType: "json",
    success: processData,
    error: function(){ alert("failed"); }
});

function processData(data)
{
    document.getElementById("game_infos").innerHTML= data.game_infos ;
    var elem = document.getElementById("player");
    var player = new WGo.BasicPlayer(elem, {
      sgf: data.sgf
      });
    window.history.pushState('page2', 'Title', data.permalink);
    document.getElementById("game_infos").innerHTML = data.game_infos ;
    document.getElementById("game-header").innerHTML= ' - ' + data.white + ' vs ' + data.black;
    document.title = data.white + ' vs ' + data.black + ' - Open Study Room';
    $("[data-toggle=tooltip]").tooltip();

};
return false;};
</script>
{% endblock %}
{% block content %}

<ul class="nav nav-tabs">
  <li ><a href="{% url 'league:archives' %}">{% trans "Archives" %}</a></li>
  {%if event not in open_events%}
  <li class="active">{{event |event_link}}</li>
    {%endif%}
  {% for ev in open_events %}
  <li {%if ev == event %} class="active"{%endif %}>
    <a href="{% url 'league:games' ev.pk %}">
      {% if ev.community %}
      ({{ev.community.slug}})
      {% endif %}
      {% if ev.is_primary %}
        <strong>
      {% endif %}
      {{ev.name}}
      {% if ev.is_primary %}
      </strong>
      {% endif %}
    </a>
  </li>
  {% endfor %}
  <li class="pull-right"><a href="{% url 'league:scrap_list' %}">{% trans "Scrape list" %}</a></li>
  </ul>
{% include 'league/includes/league_nav.html' with active='games' %}


{% include "league/includes/game_table_view.html" with event=event %}
{% endblock %}

{% block extra_js %}
{% get_current_language as LANGUAGE_CODE %}
{% include "league/includes/sgrfs_datatable.html" with sgfs_data_json=sgfs_data_json %}
{% endblock %}